# fly.toml app configuration file generated for brevity-log-shipper on 2023-05-18T19:53:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brevity-log-shipper"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  ORG = "brevity"

[metrics]
  port = 9598
  path = "/metrics"
